# Generated by Django 5.1.3 on 2025-08-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_student_score_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='security_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
